Tweaks for ergonomic linking
cloudflare/boring pull request #163
Opened 2023-09-12 21:13 UTC by molguin92

This PR is intended to make linking against a pre-compiled, FIPS-validated version of BoringSSL a bit easier and cleaner. It adds a subdir to Cargo's rustc-link-native directories and automatically sets BoringSSL's include path to `${BORING_BSSL_PATH}/include` if `BORING_BSSL_PATH` is set and `BORING_BSSL_INCLUDE_PATH` is not set.

2023-09-12 21:31 UTC, cjpatton approved these changes

2023-09-13 09:38 UTC, inikulin requested changes
Just realised that we have new features added with this release, so it's a minor version bump.

2023-09-13 09:38 UTC, inikulin commented on RELEASE_NOTES
> +3.0.5
```suggestion
3.1.0
```

2023-09-13 09:38 UTC, inikulin commented on RELEASE_NOTES
> +- 2023-09-12 Release 3.0.5
```suggestion
- 2023-09-12 Release 3.1.0
```

2023-09-13 09:38 UTC, inikulin commented on Cargo.toml
> +version = "3.0.5"
```suggestion
version = "3.1.0"
```

2023-09-13 09:39 UTC, inikulin approved these changes

2023-09-13 11:38 UTC, merged