Expose `set_compliance_policy` and `get_ciphers`
cloudflare/boring pull request #212
Opened 2024-01-16 15:12 UTC by jhoyla

Expose APIs to access `SSL_CTX_set_compliance_policy` and `SSL_CTX_get_ciphers`.

2024-01-16 16:56 UTC, ghedo commented on boring/src/ssl/mod.rs
> +/// A compliance policy
```suggestion
/// A compliance policy.
```

2024-01-16 17:22 UTC, nox commented on boring/src/ssl/mod.rs
> +    pub fn get_ciphers(&mut self) -> Result<&StackRef<SslCipher>, ErrorStack> {
This should take `&self` and you may want to put the same method on `SslContext` too.

2024-01-16 17:27 UTC, nox commented on boring/src/ssl/mod.rs
> +    pub fn get_ciphers(&mut self) -> Result<&StackRef<SslCipher>, ErrorStack> {
I don't think the Result is necessary here

https://github.com/google/boringssl/blob/b628f8721e7e67302b0e26c92e0108a31066194e/ssl/ssl_lib.cc#L2075-L2077

Seems like NULL should be interpreted as None, or even maybe that the method should panic on NULL.

https://github.com/google/boringssl/blob/master/ssl/internal.h#L631

2024-01-17 16:13 UTC, nox approved these changes

2024-01-17 16:14 UTC, nox requested changes

2024-01-17 16:14 UTC, nox commented on boring/src/ssl/mod.rs
> +    pub fn ciphers(&self) -> Option<&StackRef<SslCipher>> {
`SslContextBuilder` owns a `SslContext`, so this should just be `self.0.ciphers()`

2024-01-17 16:24 UTC, nox approved these changes

2024-01-17 16:57 UTC, merged