Expose API to enable certificate compression.
cloudflare/boring pull request #241
Opened 2024-06-18 14:29 UTC by mstyura

As a user of `tokio-boring` I'd like to control certificate compression feature using high-level Rust-friendly API instead of directly calling C functions form `boring-sys` .

2024-06-18 14:46 UTC, mstyura commented
Hello @inikulin!
Could you please review once you have time?
Thanks a lot in advance!

2025-01-06 17:11 UTC, kornelski commented on boring/src/ssl/callbacks.rs
> +        return 0;
This leaks `decompressed`?

2025-01-06 17:17 UTC, kornelski commented on boring/src/ssl/mod.rs
> +            ffi::SSL_CTX_add_cert_compression_alg(
The callbacks are per algorithm, but the ex data is per type. If `can_compress`/`can_decompress` were set dynamically, it could get the callbacks out of sync with the implementation.

Maybe this function should fail if the ex data for `C` already exists?

Also `SSL_CTX_add_cert_compression_alg` will fail if the same algorithm is set more than once, but keeps the previous callbacks still set. In the current implementation that would use old callbacks, but replace the instance of `C` regardless. It's not strictly speaking unsound since the callbacks are type-specific, but it may be surprising.

2025-02-21 10:44 UTC, kornelski requested changes
Waiting for response from the author

2025-02-21 14:37 UTC, mstyura commented on boring/src/ssl/callbacks.rs
> +        return 0;
Thanks for noticing, I've introduced wrapper type which I hope ensures correct usage of `CRYPTO_BYFFER` instance.

2025-02-21 15:21 UTC, yyaroshevich commented on boring/src/ssl/mod.rs
> +            ffi::SSL_CTX_add_cert_compression_alg(
> The callbacks are per algorithm, but the ex data is per type. If can_compress/can_decompress were set dynamically, it could get the callbacks out of sync with the implementation.

I've changed algorithm, can_compress and can_decompress to be the associated constants of trait.

> Maybe this function should fail if the ex data for C already exists?

I've changed the order of operations to only override ex data if `SSL_CTX_add_cert_compression_alg` succeed.

> Also SSL_CTX_add_cert_compression_alg will fail if the same algorithm is set more than once, but keeps the previous callbacks still set. In the current implementation that would use old callbacks, but replace the instance of C regardless. It's not strictly speaking unsound since the callbacks are type-specific, but it may be surprising.

Could you please check that with the latest changes this is no longer an issue?

2025-02-21 15:22 UTC, mstyura commented on boring/src/ssl/mod.rs
> +            ffi::SSL_CTX_add_cert_compression_alg(
> The callbacks are per algorithm, but the ex data is per type. If can_compress/can_decompress were set dynamically, it could get the callbacks out of sync with the implementation.

I've changed algorithm, can_compress and can_decompress to be the associated constants of trait.

> Maybe this function should fail if the ex data for C already exists?

I've changed the order of operations to only override ex data if `SSL_CTX_add_cert_compression_alg` succeed.

> Also SSL_CTX_add_cert_compression_alg will fail if the same algorithm is set more than once, but keeps the previous callbacks still set. In the current implementation that would use old callbacks, but replace the instance of C regardless. It's not strictly speaking unsound since the callbacks are type-specific, but it may be surprising.

Could you please check that with the latest changes this is no longer an issue?

2025-02-25 13:41 UTC, mstyura commented on boring/src/ssl/callbacks.rs
> +            boring_sys::CRYPTO_BUFFER_free(self.buffer);
Sure, I've added check.

2025-02-25 16:10 UTC, kornelski commented on boring/src/ssl/callbacks.rs
> +        let buffer = unsafe { crate::cvt_p(ffi::CRYPTO_BUFFER_alloc(&mut data, capacity))? };
This data isn't initialized, so theoretically it shouldn't be used with a Rust slice. However, the alternatives would require reinventing `Cursor`.

2025-02-25 16:10 UTC, kornelski approved these changes

2025-02-27 15:09 UTC, merged